CREATE TABLE IF NOT EXISTS Lama_Bandas (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  music_genre VARCHAR(255) NOT NULL,
  responsible VARCHAR(255) UNIQUE NOT NULL 
);


CREATE TABLE IF NOT EXISTS Lama_Shows (
  id VARCHAR(255) PRIMARY KEY,
  week_day enum('SEXTA', 'SÁBADO', 'DOMINGO') NOT NULL,
  start_time INT NOT NULL, // HORARIO EM HORA
  end_time INT NOT NULL, //HORARIO EM HORA
  band_id VARCHAR(255) NOT NULL,
  FOREIGN KEY(band_id) REFERENCES Lama_Bandas(id)
);

CREATE TABLE IF NOT EXISTS Lama_Usuarios (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role enum("NORMAL", "ADMIN") NOT NULL DEFAULT "NORMAL"
)